<?php
$kryptex_xlottery = array(
  "topo_p" => "XLOTTERY is the lottery based on the KRYPTEX Platform, the only digital lottery that pays its winnings in Dollars (USD).",
  "pagina1_p1" => "XLOTTERY is a lottery made for KRYPTEX investors, who invest their money by betting on the project, while sharing and stimulating the growth of the community and also contributing to KRYPTEX's ecosystem and development. XLOTTERY has been created with the vision of distributing profits from capture of the KRYPTEX Platform, as an incentive to all those who own and use the platform's products and services. Read further to see just how easy it is to participate in the XLOTTERY lottery.",
  "pagina1_p2" => "Bets are valid only using the KRYPTEX Token on top of this KRYPTEX Digital Currency investors, increase their chances of winnings while simultaneously boosting the sale of tokens to an ever-increasing audience. The sweepstakes will not be cumulative, every weekend there will be winners.",
  "pagina1_p3" => "By betting on XLOTTERY, not only do you have the chance to win Dollars(USD) you also gain investment in KRYPTEX, which will continue to produce a yield in your portfolio. This is truly the best way to managed an ideal effective distribution of profits from participation, in addition to the appreciation of the Kryptex Tokens and later Kryptex Digital Currency, when we launch it into the market.",
  "pagina2_titulo" => "How XLOTTERY<br/>will work",
  "pagina2_p1" => "When buying a coupon, you will choose a set of six lucky numbers on a card containing a total of 60 numbers and you must register the address of your wallet that contains the balance in KRYPTEX Token so that, in case you win, we can verify it via BSCScan thus confirming the amount of tokens required by regulation. Each sweepstakes will be broadcast live on our YouTube channel and also on our social media.",
  "pagina3_titulo" => "Growing Prize",
  "pagina3_box1_p1" => "XLottery will open when the KRYPTEX Token reaches",
  "pagina3_box1_p2" => "USD 600 <br/> Million",
  "pagina3_box1_p3" => "market capitalization, with an",
  "pagina3_box2_p1" => "estimated total prize pool of",
  "pagina3_box2_p2" => "USD 30 <br/> Million",
  "pagina3_box2_p3" => "in its opening month,",
  "pagina3_box3_p1" => "there will be",
  "pagina3_box3_p2" => "USD 1,000,000 <br/> in daily ",
  "pagina3_box3_p3" => "drawings during 30 calendar days.",
  "pagina3_p1" => "Initially this will be the opening prize, the schedule for the next drawings will be published on the Xlottery page. Gradually the prize values will be drawn according to fundraising relative to the sale of lottery tickets and the leverage gained by the KRYPTEX Token as well as the KRYPTEX Digital Currency. Just another incentive to keep your KRYPTEX tokens for the chance to win big.",
  "pagina4_titulo" => "See just how easy it is to participate in the sweepstakes",
  "pagina4_p1" => "To participate in the sweepstakes, just buy 50 dollars in KRYPTEX Token and hold your wallet, register the address of your wallet that contains the balance in KRYPTEX Token, choose 6 lucky numbers from a total of 60 numbers on the card and follow the sweepstakes through our YouTube channel. For those who received the airdrop containing a lot of 2 Kryptex Token, you can exchange them for a card on the opening day of Xlottery and choose six lucky numbers, Remember you will need to be compliant to the regulation containing 50 dollars of balance in KRYPTEX Token in your wallet to be eligible to receive winnings.",
  "pagina5_titulo" => "Example of how <br/> checks work",
  "pagina5_p1" => "In the opening month of XLOTTERY, 30 million dollars will be raffled in 30 calendar days, 1 million dollars every day, to celebrate the token's arrival at 600 million market capitalization.",
  "pagina5_p2" => "In all sweepstakes, if the winner does not have the minimum amount of 50 USD KRYPTEX Token in their wallet at the time of verification by BSCScan https://bscscan.com/, we will continue the draw until we find a wallet that complies with the regulation requirements for the delivery of the award.",
  "pagina5_p3" => "When the player buys a card and chooses the lucky numbers, the player must register a KRYPTEX Tokens wallet",
  "pagina5_p4" => "if a player wins the sweepstakes, we will use the address of the registered wallet for verification on the website https://bscscan.com/ where we verify that the winner has a balance of 50 dollars in KRYPTEX Token and is eligible to receive a prize of 1 million dollars.",
  "pagina6_titulo" => "Here your investment <br/>is guaranteed",
  "pagina6_p1" => "Unlike other lotteries, players do not lose money, as the KRYPTEX Token will remain in the players wallet and players will be able to take rises by recovering the money paid on Xlottery bets.",
  "pagina7_titulo" => "Higher chances <br/>of winning",
  "pagina7_p1" => "The chances of being a winner at XLOTTERY are higher because only those who have KRYPTEX Tokens and are within the requirements of the regulation will be able to receive the prize. The more coupons you buy, the greater your chances of winning. Bet responsibly.",
  // "pagina7_p2" => "The prize delivery will be made shortly after the wallet verification and validation process, in compliance with the regulation, it will be sent via transfer of Dollar-backed tokens, we will use Tether (USDT) and also Binance USD (BUSD) and send to the wallet registered when purchasing the ticket. It is important to inform you that all transactions intended for the payment of prizes, we will use the HASH of the transaction to be consulted and checked on the blockchain of the Binance network and will be shared on our social networks.",
  "pagina8_titulo" => "Rules",
  "pagina8_p1" => "To be eligible, the player must purchase and hold a $50 balance in KRYPTEX Token. The Prize will only be validated after verification of the wallet on BSCScan, containing the balances in KRYPTEX Token in the minimum total of 50 dollars for the prizes of 1 million dollars.",
  "pagina8_p2" => "If the player does not have a 50 USD KRYPTEX Token balance, the prize will not be awarded and the drawing will continue until a compatible wallet with a 50 USD KRYPTEX Token Balance is found.",
  "pagina8_p3" => "Xlottery is the lottery for investors on the KRYPTEX platform, so if you do not have a a minimum balance of 50 dollars worth of KRYPTEX Token in your wallet.",
  "pagina8_p4" => "we ask that you do not place a bet as you will not be eligible to receive prizes after verification on BSCScan https:// bscscan.com/ in the case of a winner and the money used to purchase the card will be nonrefundable.",
);
$lang_footer = array(
  "sub_logo" => "FROM THE FUTURE TO </br> THE PRESENT",
  "kryptex" => "KRYPTEX",
  "kryptex_token" => "KRYPTEX Token",
  "xlottery" => "XLOTTERY",
  "kryptex_pay" => "KRYPTEX <span class='baufra'>Pay</span>",
  "xnet" => "XNET",
  "kryptex_wallet" => "KRYPTEX Wallet",
  "xchange" => "XChange",
  "about" => "About"
);